### ISSUE TITLE
About code details

### ISSUE THREAD

**Issue by jieWANGforwork** [dbstjswo505/SQuiDNet#4]
Hi, thanks for your excellent work!

When reading the code, I found it is not consistent to your model in the paper, 
I'm wondering if there any detailed descriptions or interpretations for such differences, or if I misunderstood the code, could you please update mode interpretations so that I can learn from this as a beginner. 
Thank you very much if you can reply!

**Comment by dbstjswo505** [comment]
Hello, thank you for the interest
I will consider updating the code to give a more detailed explanation by giving comments on the line so that you can easily understand.
