### ISSUE TITLE
Is there a code/checkpoint for BMR, to get BMR prediction results in advance?

### ISSUE THREAD

**Issue by Yuuraa** [dbstjswo505/SQuiDNet#5]
Hello! Thank you for your great work and sharing. I love your insightful idea.

I read the code, and I have a question about BMR.

It seems that training & inference phase utilize pre-extracted BMR prediction results,
but I couldn't find the code for training the BMR module & extract the result.

Could you provide the code or a checkpoint? or could you explain how did the BMR module was trained & how did the model architecture look  & which loss was used? (as training BMR only may be hard to use moment de-biasing loss)

Thank you for your consideration :)

**Comment by dbstjswo505** [comment]
I mailed it. Thank you!

**Comment by jieWANGforwork** [comment]
> I mailed it. Thank you!

Hi, could you please email to me also for reproduce?

**Comment by zhanglong-ustc** [comment]
Hi, could you please email to me also for reproduce?

**Comment by zhanglong-ustc** [comment]
> Hello! Thank you for your great work and sharing. I love your insightful idea.
> 
> I read the code, and I have a question about BMR.
> 
> It seems that training & inference phase utilize pre-extracted BMR prediction results, but I couldn't find the code for training the BMR module & extract the result.
> 
> Could you provide the code or a checkpoint? or could you explain how did the BMR module was trained & how did the model architecture look & which loss was used? (as training BMR only may be hard to use moment de-biasing loss)
> 
> Thank you for your consideration :)

Hi, could you please email to me also for reproduce?   zhanglong.ustc@gmail.com

**Comment by hlchen23** [comment]
Hi, could you please email to me also for reproduce?

**Comment by HyunwooKims** [comment]
Hi, thank you for your greak work.
Could you please email to me also for reproduce? (sts05183@gmail.com)
